window.MC_TEXT = {
  siteTitle: "MC指令音乐站",
  logoText: "MC指令音乐站",
  searchPlaceholder: "搜索音乐或作者...",
  searchPlaceholderSmall: "搜索...",
  sortLabel: "排序",
  sortDefault: "默认顺序",
  sortNameAsc: "名称 A → Z",
  sortNameDesc: "名称 Z → A",
  sortDateDesc: "最新发布",
  sortDateAsc: "最早发布",
  downloadBtnText: "获取指令文件",
  downloadPreparing: "准备下载...",
  downloadComplete: "下载完成",
  statsLoading: "加载中...",
  statsZero: "共 0 个作品",
  emptyTitleDefault: "暂无音乐数据",
  emptyDescDefault: "请确保外部 music-data.js 存在且格式正确",
  emptyTitleNoResult: "没有找到相关资源",
  runtimePrefix: "本站已运行",
  kbdTitle: "快捷键指南",
  kbdSearch: "聚焦搜索",
  kbdEsc: "取消",
  kbdGridView: "网格视图",
  kbdListView: "列表视图",
  kbdTheme: "切换主题",
  kbdHelp: "显示帮助",
  kbdNav: "导航",
  kbdEnter: "选择",
  viewSwitchMsgGrid: "已切换到网格视图",
  viewSwitchMsgList: "已切换到列表视图",
  themeSwitchMsgDark: "已切换到深色模式",
  themeSwitchMsgLight: "已切换到浅色模式",
  dataLoadSuccessPrefix: "已加载",
  dataLoadError: "数据加载失败",
  dataInvalidTitle: "外部数据无效",
  dataInvalidDesc: "检测到 window.musicData 无效，请检查 music-data.js 格式",
  scriptLoadErrorTitle: "外部脚本加载失败",
  scriptLoadErrorDesc: "music-data.js 文件不存在或网络错误",
  randomBtnText: "随机推荐",
  dailyTitle: "今日歌单",
  dailySubPrefix: "日期: ",
  dailySubSuffix: " · 每日精选",
  toastRandomSuccess: (title) => `随机推荐：${title}`,
  toastNoRecommend: "暂无可推荐的音乐",
  toastLinkInvalid: "链接无效"
};